### ISSUE TITLE
Multiple VLAN

### ISSUE THREAD

**Issue by desmphil** [sameeraman/blog#11]
HI,

Im having the same kind of config as yourself, nice blog BTW. I was struggling between edgerouter and USG.
I'm having an issue advertising a **second subnet (VLAN) as example VLAN 5** 
(192.168.100.0/24 is well advertised, but 192.168.200.0/24 doesn't I was wondering if you could try on your side? :)

**Comment by sameeraman** [comment]
Do you have a diagram of what you are trying to achieve?

**Comment by desmphil** [comment]
I have exactly the same configuration as yours, just the ip range are different.
Look at this diagram, the only thing i added is an extra VLAN 5 on the home side.
But i can't manage to advertise it with BGP from HOME -> TO Azure
![image](https://user-images.githubusercontent.com/48382849/99922066-5d157480-2cfc-11eb-844c-b5342be676cc.png)

**Comment by sameeraman** [comment]
Because it's not listed under the advertised routes on the USG, it seems like USG is not advertising the VLAN networks (In your case VLAN 5). It's best to open a support ticket with the Unifi Support and troubleshoot it. They have a good support team. I guess it needs to be configured explicitly.

**Comment by desmphil** [comment]
Fixed, the issue was Azure,  :)
